config/routes.rb
DayTweeter::Application.routes.draw do

  root to: 'pages#home'
  
  get 'home',                     to: 'users#show',       as: :home
  get 'my/account',               to: 'users#edit',       as: :account_settings
  get 'auth/failure',             to: 'sessions#denied'
  get 'auth/twitter',                                     as: :twitter_auth
  get 'auth/:provider/callback',  to: 'sessions#create',  as: :twitter_auth_callback
  get 'signout',                  to: 'sessions#destroy', as: :signout
  
  get 'not/implemented/yet',      to: 'pages#placeholder', as: :placeholder
    
  resource :user, only: [:show, :edit, :update, :destroy]
  
  resource :system, only: [:update] do
    member do
      get 'activate'
      get 'pause'
    end
  end
  
  resources :tweets, only: [:create, :update, :destroy] do
    member do
      get 'publish'
      get 'unpublish'
      get 'enable'
      get 'disable'
    end
    collection do
      get 'clear_published'
    end
  end
  
  namespace :admin do
    mount Resque::Server, at: 'resque', as: :resque
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # twitter_id:integer
  # username
  # name
  # image
  # auth_token
  # auth_secret
  # email
  
  # attr_accessible :email, :name
  
  has_many :tweets
  has_one :system
  
  validates_presence_of :name
  
  def tweet(message)
    Twitter::Client.new(
      oauth_token:        auth_token,
      oauth_token_secret: auth_secret
    ).update(message)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
  end
  
  def edit
  end
  
  def update
    @user = current_user
    @success = @user.update_attributes(params[:user])
  end
  
  def destroy
    current_user.system.destroy
    current_user.destroy
    sign_out!
    redirect_to root_path, notice: 'Your account and all pending tweets have been deleted. Thank you for using Day Tweeter!'
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.haml
- content_for :sidebar do
  %li.nav-header Tools
  %li
    = link_to user_path do
      %i.icon-arrow-left
      Go Back
  %li
    = link_to user_path, confirm: 'Are you sure?', method: :delete, :class=>'danger' do
      %i.icon-trash
      Delete Your Account

.row
  .span5
    = form_for current_user, remote: true, html: { :class => 'form-horizontal' } do |f|
      %fieldset
        %legend Personal Information
        
        .control-group.username
          = f.label :username, 'Twitter Username', :class => 'control-label'
          .controls
            .input-prepend
              .add-on @
              = f.text_field :username, :class => 'text_field', disabled:true
            %p.help-block You cannot change your twitter username

        .control-group.name
          = f.label :name, :class => 'control-label'
          .controls
            .input-prepend
              .add-on
                %i.icon-user
              = f.text_field :name, :class => 'text_field'
    
        .control-group.email
          = f.label :email, :class => 'control-label'
          .controls
            .input-prepend
              .add-on
                %i.icon-envelope
              = f.text_field :email, :class => 'text_field'
    
        .form-actions
          = f.submit 'Save Your Info', :class => 'btn btn-primary', disable_with: 'Saving...'
          /= link_to 'Cancel', home_path, :class => 'btn'
  
  .span5
    = form_for current_user.system, remote: true, html: { :class => 'form-horizontal' } do |f|
      %fieldset
        %legend System Settings
        
        .control-group.time_zone
          = f.label :time_zone, 'Your Time Zone', :class => 'control-label'
          .controls
            = f.time_zone_select :time_zone, ActiveSupport::TimeZone.us_zones, {default:"Pacific Time (US & Canada)"}, {:class => 'span3'}
        
        .control-group.start_time_hour.start_time_min
          = f.label :start_time, 'Start Time', :class => 'control-label'
          .controls
            = f.text_field :start_time_hour, value: "%02d" % current_user.system.start_time_hour, maxsize:2, :class=>'span1third'
            \:
            = f.text_field :start_time_min, value: "%02d" % current_user.system.start_time_min, maxsize:2, :class=>'span1third'
            %span.help-inline time in 24-hour format
            %span.help-block
              This is the time the system will <strong>begin</strong> publishing tweets. If a tweet is submitted after this time, it may be published immediately.
        
        .control-group.stop_time_hour.stop_time_min
          = f.label :stop_time, 'Stop Time', :class => 'control-label'
          .controls
            = f.text_field :stop_time_hour, value: "%02d" % current_user.system.stop_time_hour, size:'1', :class=>'span1third'
            \:
            = f.text_field :stop_time_min, value: "%02d" % current_user.system.stop_time_min, size:'1', :class=>'span1third'
            %span.help-inline time in 24-hour format
            %span.help-block
              This is the time the system will <strong>stop</strong> publishing tweets for the day. If a tweet is submitted after this time, it will be published the next day.
            
        .control-group.daily_max
          = f.label :daily_max, 'Daily Maximum', :class => 'control-label'
          .controls
            = f.text_field :daily_max, :class=>'span1'
            %span.help-inline tweets per day
            %span.help-block
              The system will publish a maximum of this many tweets in a single day. Any tweets scheduled after this number is exceeded will be rolled over to the next day.
            %span.help-block
              The max potential rate (mpr) limit is 1 tweet per minute and must not be exceeded. For example, if the time between your start and stop times is 15 minutes, the daily max must be 15 or less.
  
        .form-actions
          = f.submit 'Save Your Settings', :class => 'btn btn-primary', disable_with: 'Saving...'
          /= link_to 'Cancel', home_path, :class => 'btn'

app/views/users/show.html.haml
- content_for :sidebar do
  %li.nav-header Tools
  - if current_user.system.active?
    %li
      = link_to pause_system_path do
        %i.icon-pause
        Pause Publishing
  - else
    %li
      = link_to activate_system_path, confirm:"Are you sure? As soon as the system is activated, unpublished tweets may be published immediately." do
        %i.icon-play
        Start Publishing

.well.clearfix
  = image_tag current_user.image, :class=>'avatar'
  .account-info.pull-left
    %h1= current_user.name
    %h2= "@#{current_user.username}"
    %p= current_user.email.blank? ? '&nbsp;'.html_safe : current_user.email
    .btn-group
      = link_to 'Account Settings', account_settings_path, :class=>'btn'
      %a.btn.btn-inverse.dropdown-toggle{href:'#', data:{toggle:'dropdown'}}
        %span.caret
      %ul.dropdown-menu
        %li
          = link_to account_settings_path do
            %strong Edit your settings
        %li= link_to 'Delete your account', user_path, confirm: 'Are you sure?', method: :delete
  .system-settings-summary.pull-left.span4
    %h2 Summary of Settings
    %p
      Each day, we will tweet a maximum of
      %strong= current_user.system.daily_max
      tweets from your unpublished list. These will be evenly spaced throughout the day beginning at
      = succeed ',' do
        %strong= current_user.system.start_time.hour.to_s << current_user.system.start_time.strftime(':%M %Z')
      and ending at
      = succeed '.' do
        %strong= current_user.system.stop_time.hour.to_s << current_user.system.stop_time.strftime(':%M %Z')
      Any tweets that were not published will be rolled over to the next day.
  .span2
    %h2 Status
    %p
      Day Tweeter is
      - if current_user.system.active?
        %span.label.label-success Active
      - else
        %span.label Paused
    - if current_user.system.active?
      = link_to pause_system_path, :class=>%w[btn btn-large] do
        %i.icon-pause
        Pause Publishing
    - else
      = link_to activate_system_path, :class=>%w[btn btn-large btn-success], confirm:"Are you sure? As soon as the system is activated, unpublished tweets may be published immediately." do
        %i.icon-play.icon-white
        Start Publishing
    
= form_for Tweet.new, html:{:class=>'well form-inline'} do |f|
  = f.text_field :body, rows:'1', placeholder:'Compose new Tweet...', :class=>'span8'
  = f.submit 'Save Tweet', :class=>'btn'

- if current_user.tweets.any?
  - if current_user.tweets.unpublished.any?
    %table.table.table-striped.table-bordered
      %thead
        %tr
          %th
            %h6 Unpublished Tweets
      %tbody
        - current_user.tweets.unpublished.each do |tweet|
          %tr
            
            %td.span10
              .tweet-edit.hide
                = form_for tweet, method: :put, html:{:class=>'form-inline'} do |f|
                  = f.text_field :body, placeholder:'Compose new Tweet...', :class=>'span7'
                  %button.btn.tooltip-link{type:'submit', title:'Save your changes'}
                    %i.icon-ok
                  %a.btn.btn-inverse.cancel-edit{:href => "#cancel", rel:'tooltip', title:'Discard changes'}
                    %i.icon-remove.icon-white
              
              .tweet-body
                = tweet.body
            
            %td.span2.edit-cell
              %span.pull-right
                - if tweet.pending?
                  %a.btn.disabled{rel:'tooltip', title:'This tweet is pending publishing'}
                    %i.icon-pencil
                    Edit
                - else
                  %a.btn.edit-tweet{rel:'tooltip', title:"Edit this tweet."}
                    %i.icon-pencil
                    Edit
            
            
            %td.center
              - if tweet.pending?
                - if tweet.active?
                  %a.btn.btn-primary.disabled{rel:'tooltip', title:'This tweet is pending publishing'}
                    %i.icon-time.icon-white
                - else
                  %a.btn.disabled{rel:'tooltip', title:'This tweet is pending publishing'}
                    %i.icon-minus
              - else
                - if tweet.active?
                  = link_to disable_tweet_path(tweet), :class=>%w[btn btn-primary], rel:'tooltip', title:"This tweet is active and will be published. Click to disable." do
                    %i.icon-time.icon-white
                - else
                  = link_to enable_tweet_path(tweet), :class=>'btn', rel:'tooltip', title:"This tweet is disabled and will not be published. Click to enable." do
                    %i.icon-minus
            %td.center
              - if tweet.pending?
                %a.btn.btn-success.disabled{rel:'tooltip', title:'This tweet is pending publishing'} Pending
              - else
                = link_to 'Publish', publish_tweet_path(tweet), :class=>'btn btn-success tooltip-link', title:"Manually publish this tweet to Twitter."
            %td.center
              - if tweet.pending?
                %a.btn.btn-danger.disabled{rel:'tooltip', title:'This tweet is pending publishing'}
                  %i.icon-trash.icon-white
              - else
                = link_to tweet, confirm: 'Are you sure?', method: :delete, :class=>'btn btn-danger tooltip-link', title:'Remove this tweet' do
                  %i.icon-trash.icon-white

  - if current_user.tweets.published.any?
    %table.table.table-striped.table-bordered
      %thead
        %tr
          %th
            %h6 Published Tweets
          %th
            %h6 Published
      %tbody
        - current_user.tweets.published.each do |tweet|
          %tr
            %td.span10
              .tweet_body
                = tweet.body
            %td.center
              %a.btn.btn-inverse.disabled{rel:'tooltip', title:tweet.published_at.to_formatted_s(:verbose)}= tweet.published_at.to_formatted_s(:short_ordinal_with_time)
    = link_to clear_published_tweets_path, :class=>%w[btn btn-danger pull-right], rel:'tooltip', title:"Remove all published tweets" do
      %i.icon-trash.icon-white
      Clear Published
- else
  %table.table.table-striped.table-bordered
    %thead
      %tr
        %th{colspan:4}
          %h6 Please add some Tweets above
    %tbody

app/views/users/update.js.erb
$('#flash-container').slideUp(function(){

  $('.validation-error').slideUp(function(){ $(this).remove() });
  $('.control-group').removeClass('error');

  <% if @success and !@user.errors.any? %>
    <% flash.now[:notice] = 'Your information was successfully updated' %>
  <% else %>
    <% if @user.errors.any? %>
      <% flash.now[:alert] = "#{pluralize(@user.errors.count, 'error')} prevented saving your changes" %>
      <% @user.errors.each do |field, msg| %>
        errorMessage = $('<span class="help-block validation-error"><%= escape_javascript msg %></span>');
        errorMessage.hide();
        $('.control-group.<%= escape_javascript field.to_s %>').addClass('error').find('.controls').prepend(errorMessage);
        errorMessage.slideDown();
      <% end %>
    <% else %>
      <% flash.now[:alert] = 'An unknown error prevented saving your changes' %>
    <% end %>
  <% end %>

  $(this).html("<%= escape_javascript(render partial:'shared/display_flash') %>");
  $(this).slideDown();
  
  $('.error input').focus();
  
});