config/routes.rb
DayTweeter::Application.routes.draw do

  root to: 'pages#home'
  
  get 'home',                     to: 'users#show',       as: :home
  get 'my/account',               to: 'users#edit',       as: :account_settings
  get 'auth/failure',             to: 'sessions#denied'
  get 'auth/twitter',                                     as: :twitter_auth
  get 'auth/:provider/callback',  to: 'sessions#create',  as: :twitter_auth_callback
  get 'signout',                  to: 'sessions#destroy', as: :signout
  
  get 'not/implemented/yet',      to: 'pages#placeholder', as: :placeholder
    
  resource :user, only: [:show, :edit, :update, :destroy]
  
  resource :system, only: [:update] do
    member do
      get 'activate'
      get 'pause'
    end
  end
  
  resources :tweets, only: [:create, :update, :destroy] do
    member do
      get 'publish'
      get 'unpublish'
      get 'enable'
      get 'disable'
    end
    collection do
      get 'clear_published'
    end
  end
  
  namespace :admin do
    mount Resque::Server, at: 'resque', as: :resque
  end
  
end

app/views/shared/_display_flash.html.haml
- flash.each do |name, msg|
  .flash.alert{:class=>"alert-#{name == :notice ? "success" : "error"}"}
    %a.close{data:{dismiss:'alert'}} &times;
    = msg.html_safe

app/views/shared/_navbar.html.haml
.navbar.navbar-fixed-top
  .navbar-inner
    .container
      %a.btn.btn-navbar{data:{toggle:'collapse', target:'.nav-collapse'}}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Day Tweeter', root_path, :class=>'brand'
      .nav-collapse
        %ul.nav
          / %li
          /   = link_to root_path do
          /     %i.icon-white.icon-home
          /     Home
          / %li= link_to 'Something Else'
        %ul.nav.pull-right
          - if signed_in?
            %li.dropdown
              %a.dropdown-toggle{href:'#', data:{toggle:'dropdown'}}
                = image_tag current_user.image
                = '@' << current_user.username
                %b.caret
              %ul.dropdown-menu
                %li
                  = link_to home_path do
                    %i.icon-user
                    Home
                %li
                  = link_to account_settings_path do
                    %i.icon-edit
                    Settings
                %li.divider
                %li
                  = link_to signout_path do
                    %i.icon-off
                    Sign Out
          - else
            %li
              = link_to twitter_auth_path, :class=>'' do
                %i.icon-white.icon-user
                Sign in with Twitter
              

app/views/shared/_sidebar.html.haml
.well{style:'padding: 8px 0;'}
  %ul.nav.nav-list
    = yield :sidebar
    %li.nav-header Navigation
    %li
      = link_to admin_resque_path do
        %i.icon-lock
        Admin
    %li
      = link_to home_path do
        %i.icon-home
        Home
    - if signed_in?
      %li
        = link_to account_settings_path do
          %i.icon-edit
          Settings
      %li
        = link_to signout_path do
          %i.icon-off
          Sign Out
    - else
      %li
        = link_to twitter_auth_path do
          %i.icon-user
          Sign in
      